# Generated by Django 5.1.6 on 2025-03-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=15)),
                ('group_image', models.ImageField(upload_to='group_image/')),
                ('group_members', models.ManyToManyField(blank=True, to='backend.user')),
            ],
        ),
    ]
