# Generated by Django 5.1.6 on 2025-03-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('reciever', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
